<?php

namespace App\Command;

use App\Entity\AdminSidebarTheme;
use App\Repository\AdminSidebarThemeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

/**
 * Crée (ou met à jour si déjà présents) les thèmes de sidebar admin de
 * départ : Émeraude, Indigo Clair, Nuit. À exécuter une fois après la
 * migration qui crée la table admin_sidebar_theme.
 *
 * php bin/console app:seed-admin-sidebar-themes
 */
#[AsCommand(
    name: 'app:seed-admin-sidebar-themes',
    description: 'Crée ou met à jour les thèmes de sidebar admin de départ (Émeraude, Indigo Clair, Nuit)',
)]
class SeedAdminSidebarThemesCommand extends Command
{
    public function __construct(
        private readonly AdminSidebarThemeRepository $repository,
        private readonly EntityManagerInterface $em,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $themes = [
            [
                'name' => 'Émeraude',
                'bgColor' => '#FFFFFF',
                'textColor' => '#854747',
                'hoverBgColor' => '#F9EBEB',
                'hoverTextColor' => '#6F2020',
                'activeBgColor' => '#D24141',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BD7575',
            ],
            [
                'name' => 'Indigo Clair',
                'bgColor' => '#321C1A',
                'textColor' => '#BC938F',
                'hoverBgColor' => '#4A2926',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#D24E41',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#AC726C',
            ],
            [
                'name' => 'Nuit',
                'bgColor' => '#FFFFFF',
                'textColor' => '#855247',
                'hoverBgColor' => '#F9EEEB',
                'hoverTextColor' => '#6F2E20',
                'activeBgColor' => '#D25A41',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BD8275',
            ],
            [
                'name' => 'Corail',
                'bgColor' => '#32201A',
                'textColor' => '#BC9B8F',
                'hoverBgColor' => '#4A3026',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#D26741',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#AC7D6C',
            ],
            [
                'name' => 'Améthyste',
                'bgColor' => '#FFFFFF',
                'textColor' => '#855D47',
                'hoverBgColor' => '#F9F0EB',
                'hoverTextColor' => '#6F3B20',
                'activeBgColor' => '#D27441',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BD8E75',
            ],
            [
                'name' => 'Océan',
                'bgColor' => '#32251A',
                'textColor' => '#BCA38F',
                'hoverBgColor' => '#4A3626',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#D28041',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#AC886C',
            ],
            [
                'name' => 'Graphite',
                'bgColor' => '#FFFFFF',
                'textColor' => '#856747',
                'hoverBgColor' => '#F9F3EB',
                'hoverTextColor' => '#6F4920',
                'activeBgColor' => '#D28D41',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BD9B75',
            ],
            [
                'name' => 'Sable',
                'bgColor' => '#32291A',
                'textColor' => '#BCAB8F',
                'hoverBgColor' => '#4A3C26',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#D29A41',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#AC936C',
            ],
            [
                'name' => 'Kendra',
                'bgColor' => '#FFFFFF',
                'textColor' => '#857247',
                'hoverBgColor' => '#F9F5EB',
                'hoverTextColor' => '#6F5720',
                'activeBgColor' => '#D2A641',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BDA775',
            ],
            [
                'name' => 'Kenan',
                'bgColor' => '#322D1A',
                'textColor' => '#BCB28F',
                'hoverBgColor' => '#4A4226',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#D2B341',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#AC9E6C',
            ],
            [
                'name' => 'Isabelle',
                'bgColor' => '#FFFFFF',
                'textColor' => '#857D47',
                'hoverBgColor' => '#F9F7EB',
                'hoverTextColor' => '#6F6420',
                'activeBgColor' => '#D2BF41',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BDB375',
            ],
            [
                'name' => 'Sublime',
                'bgColor' => '#32311A',
                'textColor' => '#BCBA8F',
                'hoverBgColor' => '#4A4826',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#D2CC41',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#ACAA6C',
            ],
            [
                'name' => 'Marthe',
                'bgColor' => '#FFFFFF',
                'textColor' => '#828547',
                'hoverBgColor' => '#F9F9EB',
                'hoverTextColor' => '#6B6F20',
                'activeBgColor' => '#CCD241',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BABD75',
            ],
            [
                'name' => 'Yavhette',
                'bgColor' => '#2F321A',
                'textColor' => '#B6BC8F',
                'hoverBgColor' => '#454A26',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#BFD241',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#A4AC6C',
            ],
            [
                'name' => 'Candy',
                'bgColor' => '#FFFFFF',
                'textColor' => '#778547',
                'hoverBgColor' => '#F6F9EB',
                'hoverTextColor' => '#5E6F20',
                'activeBgColor' => '#B3D241',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#ADBD75',
            ],
            [
                'name' => 'Logan',
                'bgColor' => '#2B321A',
                'textColor' => '#AEBC8F',
                'hoverBgColor' => '#3F4A26',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#A6D241',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#99AC6C',
            ],
            [
                'name' => 'Yvana',
                'bgColor' => '#FFFFFF',
                'textColor' => '#6D8547',
                'hoverBgColor' => '#F4F9EB',
                'hoverTextColor' => '#506F20',
                'activeBgColor' => '#9AD241',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#A1BD75',
            ],
            [
                'name' => 'Auguste',
                'bgColor' => '#27321A',
                'textColor' => '#A7BC8F',
                'hoverBgColor' => '#394A26',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#8DD241',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#8EAC6C',
            ],
            [
                'name' => 'Stephie',
                'bgColor' => '#FFFFFF',
                'textColor' => '#628547',
                'hoverBgColor' => '#F1F9EB',
                'hoverTextColor' => '#426F20',
                'activeBgColor' => '#80D241',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#94BD75',
            ],
            [
                'name' => 'Coco',
                'bgColor' => '#23321A',
                'textColor' => '#9FBC8F',
                'hoverBgColor' => '#334A26',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#74D241',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#82AC6C',
            ],
            [
                'name' => 'Kemy',
                'bgColor' => '#FFFFFF',
                'textColor' => '#578547',
                'hoverBgColor' => '#EFF9EB',
                'hoverTextColor' => '#356F20',
                'activeBgColor' => '#67D241',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#88BD75',
            ],
            [
                'name' => 'Maguy',
                'bgColor' => '#1E321A',
                'textColor' => '#97BC8F',
                'hoverBgColor' => '#2C4A26',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#5AD241',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#77AC6C',
            ],
            [
                'name' => 'Nathalie',
                'bgColor' => '#FFFFFF',
                'textColor' => '#4D8547',
                'hoverBgColor' => '#ECF9EB',
                'hoverTextColor' => '#276F20',
                'activeBgColor' => '#4ED241',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#7CBD75',
            ],
            [
                'name' => 'Gisèle',
                'bgColor' => '#1A321A',
                'textColor' => '#8FBC8F',
                'hoverBgColor' => '#264A26',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#41D241',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#6CAC6C',
            ],
            [
                'name' => 'Nancy',
                'bgColor' => '#FFFFFF',
                'textColor' => '#47854D',
                'hoverBgColor' => '#EBF9EC',
                'hoverTextColor' => '#206F27',
                'activeBgColor' => '#41D24E',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#75BD7C',
            ],
            [
                'name' => 'Alexis',
                'bgColor' => '#1A321E',
                'textColor' => '#8FBC97',
                'hoverBgColor' => '#264A2C',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#41D25A',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#6CAC77',
            ],
            [
                'name' => 'Sébastien',
                'bgColor' => '#FFFFFF',
                'textColor' => '#478557',
                'hoverBgColor' => '#EBF9EF',
                'hoverTextColor' => '#206F35',
                'activeBgColor' => '#41D267',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#75BD88',
            ],
            [
                'name' => 'Freddy',
                'bgColor' => '#1A3223',
                'textColor' => '#8FBC9F',
                'hoverBgColor' => '#264A33',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#41D274',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#6CAC82',
            ],
            [
                'name' => 'Patrick',
                'bgColor' => '#FFFFFF',
                'textColor' => '#478562',
                'hoverBgColor' => '#EBF9F1',
                'hoverTextColor' => '#206F42',
                'activeBgColor' => '#41D280',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#75BD94',
            ],
            [
                'name' => 'Oceana',
                'bgColor' => '#1A3227',
                'textColor' => '#8FBCA7',
                'hoverBgColor' => '#264A39',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#41D28D',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#6CAC8E',
            ],
            [
                'name' => 'Eulielna',
                'bgColor' => '#FFFFFF',
                'textColor' => '#47856D',
                'hoverBgColor' => '#EBF9F4',
                'hoverTextColor' => '#206F50',
                'activeBgColor' => '#41D29A',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#75BDA1',
            ],
            [
                'name' => 'Dolcy',
                'bgColor' => '#1A322B',
                'textColor' => '#8FBCAE',
                'hoverBgColor' => '#264A3F',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#41D2A6',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#6CAC99',
            ],
            [
                'name' => 'Edd',
                'bgColor' => '#FFFFFF',
                'textColor' => '#478577',
                'hoverBgColor' => '#EBF9F6',
                'hoverTextColor' => '#206F5E',
                'activeBgColor' => '#41D2B3',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#75BDAD',
            ],
            [
                'name' => 'Yoanna',
                'bgColor' => '#1A322F',
                'textColor' => '#8FBCB6',
                'hoverBgColor' => '#264A45',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#41D2BF',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#6CACA4',
            ],
            [
                'name' => 'Précieux',
                'bgColor' => '#FFFFFF',
                'textColor' => '#478582',
                'hoverBgColor' => '#EBF9F9',
                'hoverTextColor' => '#206F6B',
                'activeBgColor' => '#41D2CC',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#75BDBA',
            ],
            [
                'name' => 'Jovy',
                'bgColor' => '#1A3132',
                'textColor' => '#8FBABC',
                'hoverBgColor' => '#26484A',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#41CCD2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#6CAAAC',
            ],
            [
                'name' => 'Karcel',
                'bgColor' => '#FFFFFF',
                'textColor' => '#477D85',
                'hoverBgColor' => '#EBF7F9',
                'hoverTextColor' => '#20646F',
                'activeBgColor' => '#41BFD2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#75B3BD',
            ],
            [
                'name' => 'Chloé',
                'bgColor' => '#1A2D32',
                'textColor' => '#8FB2BC',
                'hoverBgColor' => '#26424A',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#41B3D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#6C9EAC',
            ],
            [
                'name' => 'Saab',
                'bgColor' => '#FFFFFF',
                'textColor' => '#477285',
                'hoverBgColor' => '#EBF5F9',
                'hoverTextColor' => '#20576F',
                'activeBgColor' => '#41A6D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#75A7BD',
            ],
            [
                'name' => 'Ryan',
                'bgColor' => '#1A2932',
                'textColor' => '#8FABBC',
                'hoverBgColor' => '#263C4A',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#419AD2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#6C93AC',
            ],
            [
                'name' => 'Djojo',
                'bgColor' => '#FFFFFF',
                'textColor' => '#476785',
                'hoverBgColor' => '#EBF3F9',
                'hoverTextColor' => '#20496F',
                'activeBgColor' => '#418DD2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#759BBD',
            ],
            [
                'name' => 'Junior',
                'bgColor' => '#1A2532',
                'textColor' => '#8FA3BC',
                'hoverBgColor' => '#26364A',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#4180D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#6C88AC',
            ],
            [
                'name' => 'Pyrens',
                'bgColor' => '#FFFFFF',
                'textColor' => '#475D85',
                'hoverBgColor' => '#EBF0F9',
                'hoverTextColor' => '#203B6F',
                'activeBgColor' => '#4174D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#758EBD',
            ],
            [
                'name' => 'Martha',
                'bgColor' => '#1A2032',
                'textColor' => '#8F9BBC',
                'hoverBgColor' => '#26304A',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#4167D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#6C7DAC',
            ],
            [
                'name' => 'Jaden',
                'bgColor' => '#FFFFFF',
                'textColor' => '#475285',
                'hoverBgColor' => '#EBEEF9',
                'hoverTextColor' => '#202E6F',
                'activeBgColor' => '#415AD2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#7582BD',
            ],
            [
                'name' => 'Live',
                'bgColor' => '#1A1C32',
                'textColor' => '#8F93BC',
                'hoverBgColor' => '#26294A',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#414ED2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#6C72AC',
            ],
            [
                'name' => 'Grace',
                'bgColor' => '#FFFFFF',
                'textColor' => '#474785',
                'hoverBgColor' => '#EBEBF9',
                'hoverTextColor' => '#20206F',
                'activeBgColor' => '#4141D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#7575BD',
            ],
            [
                'name' => 'Fanny',
                'bgColor' => '#1C1A32',
                'textColor' => '#938FBC',
                'hoverBgColor' => '#29264A',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#4E41D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#726CAC',
            ],
            [
                'name' => 'Gloire',
                'bgColor' => '#FFFFFF',
                'textColor' => '#524785',
                'hoverBgColor' => '#EEEBF9',
                'hoverTextColor' => '#2E206F',
                'activeBgColor' => '#5A41D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#8275BD',
            ],
            [
                'name' => 'Esther',
                'bgColor' => '#201A32',
                'textColor' => '#9B8FBC',
                'hoverBgColor' => '#30264A',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#6741D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#7D6CAC',
            ],
            [
                'name' => 'Fideldi',
                'bgColor' => '#FFFFFF',
                'textColor' => '#5D4785',
                'hoverBgColor' => '#F0EBF9',
                'hoverTextColor' => '#3B206F',
                'activeBgColor' => '#7441D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#8E75BD',
            ],
            [
                'name' => 'Flo',
                'bgColor' => '#251A32',
                'textColor' => '#A38FBC',
                'hoverBgColor' => '#36264A',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#8041D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#886CAC',
            ],
            [
                'name' => 'Doudou',
                'bgColor' => '#FFFFFF',
                'textColor' => '#674785',
                'hoverBgColor' => '#F3EBF9',
                'hoverTextColor' => '#49206F',
                'activeBgColor' => '#8D41D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#9B75BD',
            ],
            [
                'name' => 'Orianne',
                'bgColor' => '#291A32',
                'textColor' => '#AB8FBC',
                'hoverBgColor' => '#3C264A',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#9A41D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#936CAC',
            ],
            [
                'name' => 'Claudine',
                'bgColor' => '#FFFFFF',
                'textColor' => '#724785',
                'hoverBgColor' => '#F5EBF9',
                'hoverTextColor' => '#57206F',
                'activeBgColor' => '#A641D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#A775BD',
            ],
            [
                'name' => 'Nivelle',
                'bgColor' => '#2D1A32',
                'textColor' => '#B28FBC',
                'hoverBgColor' => '#42264A',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#B341D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#9E6CAC',
            ],
            [
                'name' => 'Dessy',
                'bgColor' => '#FFFFFF',
                'textColor' => '#7D4785',
                'hoverBgColor' => '#F7EBF9',
                'hoverTextColor' => '#64206F',
                'activeBgColor' => '#BF41D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#B375BD',
            ],
            [
                'name' => 'Doly',
                'bgColor' => '#311A32',
                'textColor' => '#BA8FBC',
                'hoverBgColor' => '#48264A',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#CC41D2',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#AA6CAC',
            ],
            [
                'name' => 'Filhyo',
                'bgColor' => '#FFFFFF',
                'textColor' => '#854782',
                'hoverBgColor' => '#F9EBF9',
                'hoverTextColor' => '#6F206B',
                'activeBgColor' => '#D241CC',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BD75BA',
            ],
            [
                'name' => 'Dan',
                'bgColor' => '#321A2F',
                'textColor' => '#BC8FB6',
                'hoverBgColor' => '#4A2645',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#D241BF',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#AC6CA4',
            ],
            [
                'name' => 'Candy3',
                'bgColor' => '#FFFFFF',
                'textColor' => '#854777',
                'hoverBgColor' => '#F9EBF6',
                'hoverTextColor' => '#6F205E',
                'activeBgColor' => '#D241B3',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BD75AD',
            ],
            [
                'name' => 'CandyM',
                'bgColor' => '#321A2B',
                'textColor' => '#BC8FAE',
                'hoverBgColor' => '#4A263F',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#D241A6',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#AC6C99',
            ],
            [
                'name' => 'Hugo',
                'bgColor' => '#FFFFFF',
                'textColor' => '#85476D',
                'hoverBgColor' => '#F9EBF4',
                'hoverTextColor' => '#6F2050',
                'activeBgColor' => '#D2419A',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BD75A1',
            ],
            [
                'name' => 'Shama',
                'bgColor' => '#321A27',
                'textColor' => '#BC8FA7',
                'hoverBgColor' => '#4A2639',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#D2418D',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#AC6C8E',
            ],
            [
                'name' => 'Urielle',
                'bgColor' => '#FFFFFF',
                'textColor' => '#854762',
                'hoverBgColor' => '#F9EBF1',
                'hoverTextColor' => '#6F2042',
                'activeBgColor' => '#D24180',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BD7594',
            ],
            [
                'name' => 'Luc',
                'bgColor' => '#321A23',
                'textColor' => '#BC8F9F',
                'hoverBgColor' => '#4A2633',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#D24174',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#AC6C82',
            ],
            [
                'name' => 'Joy',
                'bgColor' => '#FFFFFF',
                'textColor' => '#854757',
                'hoverBgColor' => '#F9EBEF',
                'hoverTextColor' => '#6F2035',
                'activeBgColor' => '#D24167',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BD7588',
            ],
            [
                'name' => 'Enodicia',
                'bgColor' => '#321A1E',
                'textColor' => '#BC8F97',
                'hoverBgColor' => '#4A262C',
                'hoverTextColor' => '#FFFFFF',
                'activeBgColor' => '#D2415A',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#AC6C77',
            ],
            [
                'name' => 'Tiphanie',
                'bgColor' => '#FFFFFF',
                'textColor' => '#85474D',
                'hoverBgColor' => '#F9EBEC',
                'hoverTextColor' => '#6F2027',
                'activeBgColor' => '#D2414E',
                'activeTextColor' => '#FFFFFF',
                'iconColor' => '#BD757C',
            ],
        ];
        $created = 0;
        $updated = 0;

        foreach ($themes as $data) {
            $theme = $this->repository->findOneBy(['name' => $data['name']]);
            if (!$theme) {
                $theme = new AdminSidebarTheme();
                $theme->setName($data['name']);
                $this->em->persist($theme);
                $created++;
            } else {
                $updated++;
            }

            $theme->setBgColor($data['bgColor']);
            $theme->setTextColor($data['textColor']);
            $theme->setHoverBgColor($data['hoverBgColor']);
            $theme->setHoverTextColor($data['hoverTextColor']);
            $theme->setActiveBgColor($data['activeBgColor']);
            $theme->setActiveTextColor($data['activeTextColor']);
            $theme->setIconColor($data['iconColor']);
        }

        $this->em->flush();

        $io->success(sprintf('%d thème(s) créé(s), %d thème(s) mis à jour.', $created, $updated));

        return Command::SUCCESS;
    }
}