vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: /media/products
            upload_destination: '%env(UPLOADS_PUBLIC_PATH)%/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        private_documents:
            uri_prefix: /internal-storage
            upload_destination: '%env(UPLOADS_PRIVATE_PATH)%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        # mapping pour les visuels publicitaires
        ad_banners:
            uri_prefix: /media/ads
            upload_destination: '%env(UPLOADS_PUBLIC_PATH)%/ads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        category_illustrations:
            uri_prefix: /media/illustrations
            upload_destination: '%env(UPLOADS_PUBLIC_PATH)%/illustrations'
            namer: App\Uploader\Namer\CategoryIllustrationNamer

        logos_brands:
            uri_prefix: /media/logos_brands
            upload_destination: '%env(UPLOADS_PUBLIC_PATH)%/logos_brands'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        part_catalog_images:
            uri_prefix: /media/part_catalog_images
            upload_destination: '%env(UPLOADS_PUBLIC_PATH)%/part_catalog_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        seo_og_images:
            uri_prefix: /media/seo_og
            upload_destination: '%env(UPLOADS_PUBLIC_PATH)%/seo_og'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    
        site_identity_source:
            uri_prefix: /media/site_identity
            upload_destination: '%env(UPLOADS_PUBLIC_PATH)%/site_identity'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer