<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260802002955 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pays (id INT AUTO_INCREMENT NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, iso2 VARCHAR(2) NOT NULL, iso3 VARCHAR(3) NOT NULL, phone_code VARCHAR(10) NOT NULL, flag VARCHAR(10) DEFAULT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('INSERT INTO pays (name_fr, name_en, iso2, iso3, phone_code, flag) VALUES (\'Afghanistan\', \'Afghanistan\', \'AF\', \'AFG\', \'93\', \'🇦🇫\'), (\'Afrique du Sud\', \'South Africa\', \'ZA\', \'ZAF\', \'27\', \'🇿🇦\'), (\'Albanie\', \'Albania\', \'AL\', \'ALB\', \'355\', \'🇦🇱\'), (\'Algérie\', \'Algeria\', \'DZ\', \'DZA\', \'213\', \'🇩🇿\'), (\'Allemagne\', \'Germany\', \'DE\', \'DEU\', \'49\', \'🇩🇪\'), (\'Andorre\', \'Andorra\', \'AD\', \'AND\', \'376\', \'🇦🇩\'), (\'Angola\', \'Angola\', \'AO\', \'AGO\', \'244\', \'🇦🇴\'), (\'Antigua-et-Barbuda\', \'Antigua and Barbuda\', \'AG\', \'ATG\', \'1268\', \'🇦🇬\'), (\'Arabie Saoudite\', \'Saudi Arabia\', \'SA\', \'SAU\', \'966\', \'🇸🇦\'), (\'Argentine\', \'Argentina\', \'AR\', \'ARG\', \'54\', \'🇦🇷\'), (\'Arménie\', \'Armenia\', \'AM\', \'ARM\', \'374\', \'🇦🇲\'), (\'Australie\', \'Australia\', \'AU\', \'AUS\', \'61\', \'🇦🇺\'), (\'Autriche\', \'Austria\', \'AT\', \'AUT\', \'43\', \'🇦🇹\'), (\'Azerbaïdjan\', \'Azerbaijan\', \'AZ\', \'AZE\', \'994\', \'🇦🇿\'), (\'Bahamas\', \'Bahamas\', \'BS\', \'BHS\', \'1242\', \'🇧🇸\'), (\'Bahreïn\', \'Bahrain\', \'BH\', \'BHR\', \'973\', \'🇧🇭\'), (\'Bangladesh\', \'Bangladesh\', \'BD\', \'BGD\', \'880\', \'🇧🇩\'), (\'Barbade\', \'Barbados\', \'BB\', \'BRB\', \'1246\', \'🇧🇧\'), (\'Belgique\', \'Belgium\', \'BE\', \'BEL\', \'32\', \'🇧🇪\'), (\'Bénin\', \'Benin\', \'BJ\', \'BEN\', \'229\', \'🇧🇯\'), (\'Bhoutan\', \'Bhutan\', \'BT\', \'BTN\', \'975\', \'🇧🇹\'), (\'Biélorussie\', \'Belarus\', \'BY\', \'BLR\', \'375\', \'🇧🇾\'), (\'Birmanie (Myanmar)\', \'Myanmar\', \'MM\', \'MMR\', \'95\', \'🇲🇲\'), (\'Bolivie\', \'Bolivia\', \'BO\', \'BOL\', \'591\', \'🇧🇴\'), (\'Bosnie-Herzégovine\', \'Bosnia and Herzegovina\', \'BA\', \'BIH\', \'387\', \'🇧🇦\'), (\'Botswana\', \'Botswana\', \'BW\', \'BWA\', \'267\', \'🇧🇼\'), (\'Brésil\', \'Brazil\', \'BR\', \'BRA\', \'55\', \'🇧🇷\'), (\'Brunei\', \'Brunei\', \'BN\', \'BRN\', \'673\', \'🇧🇳\'), (\'Bulgarie\', \'Bulgaria\', \'BG\', \'BGR\', \'359\', \'🇧🇬\'), (\'Burkina Faso\', \'Burkina Faso\', \'BF\', \'BFA\', \'226\', \'🇧🇫\'), (\'Burundi\', \'Burundi\', \'BI\', \'BDI\', \'257\', \'🇧🇮\'), (\'Cambodge\', \'Cambodia\', \'KH\', \'KHM\', \'855\', \'🇰🇭\'), (\'Cameroun\', \'Cameroon\', \'CM\', \'CMR\', \'237\', \'🇨🇲\'), (\'Canada\', \'Canada\', \'CA\', \'CAN\', \'1\', \'🇨🇦\'), (\'Cap-Vert\', \'Cape Verde\', \'CV\', \'CPV\', \'238\', \'🇨🇻\'), (\'Chili\', \'Chile\', \'CL\', \'CHL\', \'56\', \'🇨🇱\'), (\'Chine\', \'China\', \'CN\', \'CHN\', \'86\', \'🇨🇳\'), (\'Chypre\', \'Cyprus\', \'CY\', \'CYP\', \'357\', \'🇨🇾\'), (\'Colombie\', \'Colombia\', \'CO\', \'COL\', \'57\', \'🇨🇴\'), (\'Comores\', \'Comoros\', \'KM\', \'COM\', \'269\', \'🇰🇲\');');
        $this->addSql('INSERT INTO pays (name_fr, name_en, iso2, iso3, phone_code, flag) VALUES (\'Congo (Brazzaville)\', \'Republic of the Congo\', \'CG\', \'COG\', \'242\', \'🇨🇬\'), (\'Congo (RDC)\', \'Democratic Republic of the Congo\', \'CD\', \'COD\', \'243\', \'🇨🇩\'), (\'Corée du Nord\', \'North Korea\', \'KP\', \'PRK\', \'850\', \'🇰🇵\'), (\'Corée du Sud\', \'South Korea\', \'KR\', \'KOR\', \'82\', \'🇰🇷\'), (\'Costa Rica\', \'Costa Rica\', \'CR\', \'CRI\', \'506\', \'🇨🇷\'), (\'Côte d’Ivoire\', \'Ivory Coast\', \'CI\', \'CIV\', \'225\', \'🇨🇮\'), (\'Croatie\', \'Croatia\', \'HR\', \'HRV\', \'385\', \'🇭🇷\'), (\'Cuba\', \'Cuba\', \'CU\', \'CUB\', \'53\', \'🇨🇺\'), (\'Danemark\', \'Denmark\', \'DK\', \'DNK\', \'45\', \'🇩🇰\'), (\'Djibouti\', \'Djibouti\', \'DJ\', \'DJI\', \'253\', \'🇩🇯\'), (\'Dominique\', \'Dominica\', \'DM\', \'DMA\', \'1767\', \'🇩🇲\'), (\'Égypte\', \'Egypt\', \'EG\', \'EGY\', \'20\', \'🇪🇬\'), (\'Émirats arabes unis\', \'United Arab Emirates\', \'AE\', \'ARE\', \'971\', \'🇦🇪\'), (\'Équateur\', \'Ecuador\', \'EC\', \'ECU\', \'593\', \'🇪🇨\'), (\'Érythrée\', \'Eritrea\', \'ER\', \'ERI\', \'291\', \'🇪🇷\'), (\'Espagne\', \'Spain\', \'ES\', \'ESP\', \'34\', \'🇪🇸\'), (\'Estonie\', \'Estonia\', \'EE\', \'EST\', \'372\', \'🇪🇪\'), (\'Eswatini\', \'Eswatini\', \'SZ\', \'SWZ\', \'268\', \'🇸🇿\'), (\'États-Unis\', \'United States\', \'US\', \'USA\', \'1\', \'🇺🇸\'), (\'Éthiopie\', \'Ethiopia\', \'ET\', \'ETH\', \'251\', \'🇪🇹\'), (\'Fidji\', \'Fiji\', \'FJ\', \'FJI\', \'679\', \'🇫🇯\'), (\'Finlande\', \'Finland\', \'FI\', \'FIN\', \'358\', \'🇫🇮\'), (\'France\', \'France\', \'FR\', \'FRA\', \'33\', \'🇫🇷\'), (\'Gabon\', \'Gabon\', \'GA\', \'GAB\', \'241\', \'🇬🇦\'), (\'Gambie\', \'Gambia\', \'GM\', \'GMB\', \'220\', \'🇬🇲\'), (\'Géorgie\', \'Georgia\', \'GE\', \'GEO\', \'995\', \'🇬🇪\'), (\'Ghana\', \'Ghana\', \'GH\', \'GHA\', \'233\', \'🇬🇭\'), (\'Grèce\', \'Greece\', \'GR\', \'GRC\', \'30\', \'🇬🇷\'), (\'Grenade\', \'Grenada\', \'GD\', \'GRD\', \'1473\', \'🇬🇩\'), (\'Guatemala\', \'Guatemala\', \'GT\', \'GTM\', \'502\', \'🇬🇹\'), (\'Guinée\', \'Guinea\', \'GN\', \'GIN\', \'224\', \'🇬🇳\'), (\'Guinée équatoriale\', \'Equatorial Guinea\', \'GQ\', \'GNQ\', \'240\', \'🇬🇶\'), (\'Guinée-Bissau\', \'Guinea-Bissau\', \'GW\', \'GNB\', \'245\', \'🇬🇼\'), (\'Guyana\', \'Guyana\', \'GY\', \'GUY\', \'592\', \'🇬🇾\'), (\'Haïti\', \'Haiti\', \'HT\', \'HTI\', \'509\', \'🇭🇹\'), (\'Honduras\', \'Honduras\', \'HN\', \'HND\', \'504\', \'🇭🇳\'), (\'Hongrie\', \'Hungary\', \'HU\', \'HUN\', \'36\', \'🇭🇺\'), (\'Inde\', \'India\', \'IN\', \'IND\', \'91\', \'🇮🇳\'), (\'Indonésie\', \'Indonesia\', \'ID\', \'IDN\', \'62\', \'🇮🇩\'), (\'Irak\', \'Iraq\', \'IQ\', \'IRQ\', \'964\', \'🇮🇶\');');
        $this->addSql('INSERT INTO pays (name_fr, name_en, iso2, iso3, phone_code, flag) VALUES (\'Iran\', \'Iran\', \'IR\', \'IRN\', \'98\', \'🇮🇷\'), (\'Irlande\', \'Ireland\', \'IE\', \'IRL\', \'353\', \'🇮🇪\'), (\'Islande\', \'Iceland\', \'IS\', \'ISL\', \'354\', \'🇮🇸\'), (\'Israël\', \'Israel\', \'IL\', \'ISR\', \'972\', \'🇮🇱\'), (\'Italie\', \'Italy\', \'IT\', \'ITA\', \'39\', \'🇮🇹\'), (\'Jamaïque\', \'Jamaica\', \'JM\', \'JAM\', \'1876\', \'🇯🇲\'), (\'Japon\', \'Japan\', \'JP\', \'JPN\', \'81\', \'🇯🇵\'), (\'Jordanie\', \'Jordan\', \'JO\', \'JOR\', \'962\', \'🇯🇴\'), (\'Kazakhstan\', \'Kazakhstan\', \'KZ\', \'KAZ\', \'7\', \'🇰🇿\'), (\'Kenya\', \'Kenya\', \'KE\', \'KEN\', \'254\', \'🇰🇪\'), (\'Kirghizistan\', \'Kyrgyzstan\', \'KG\', \'KGZ\', \'996\', \'🇰🇬\'), (\'Kiribati\', \'Kiribati\', \'KI\', \'KIR\', \'686\', \'🇰🇮\'), (\'Koweït\', \'Kuwait\', \'KW\', \'KWT\', \'965\', \'🇰🇼\'), (\'Laos\', \'Laos\', \'LA\', \'LAO\', \'856\', \'🇱🇦\'), (\'Lesotho\', \'Lesotho\', \'LS\', \'LSO\', \'266\', \'🇱🇸\'), (\'Lettonie\', \'Latvia\', \'LV\', \'LVA\', \'371\', \'🇱🇻\'), (\'Liban\', \'Lebanon\', \'LB\', \'LBN\', \'961\', \'🇱🇧\'), (\'Libéria\', \'Liberia\', \'LR\', \'LBR\', \'231\', \'🇱🇷\'), (\'Libye\', \'Libya\', \'LY\', \'LBY\', \'218\', \'🇱🇾\'), (\'Liechtenstein\', \'Liechtenstein\', \'LI\', \'LIE\', \'423\', \'🇱🇮\'), (\'Lituanie\', \'Lithuania\', \'LT\', \'LTU\', \'370\', \'🇱🇹\'), (\'Luxembourg\', \'Luxembourg\', \'LU\', \'LUX\', \'352\', \'🇱🇺\'), (\'Macédoine du Nord\', \'North Macedonia\', \'MK\', \'MKD\', \'389\', \'🇲🇰\'), (\'Madagascar\', \'Madagascar\', \'MG\', \'MDG\', \'261\', \'🇲🇬\'), (\'Malaisie\', \'Malaysia\', \'MY\', \'MYS\', \'60\', \'🇲🇾\'), (\'Malawi\', \'Malawi\', \'MW\', \'MWI\', \'265\', \'🇲🇼\'), (\'Maldives\', \'Maldives\', \'MV\', \'MDV\', \'960\', \'🇲🇻\'), (\'Mali\', \'Mali\', \'ML\', \'MLI\', \'223\', \'🇲🇱\'), (\'Malte\', \'Malta\', \'MT\', \'MLT\', \'356\', \'🇲🇹\'), (\'Maroc\', \'Morocco\', \'MA\', \'MAR\', \'212\', \'🇲🇦\'), (\'Maurice\', \'Mauritius\', \'MU\', \'MUS\', \'230\', \'🇲🇺\'), (\'Mauritanie\', \'Mauritania\', \'MR\', \'MRT\', \'222\', \'🇲🇷\'), (\'Mexique\', \'Mexico\', \'MX\', \'MEX\', \'52\', \'🇲🇽\'), (\'Micronésie\', \'Micronesia\', \'FM\', \'FSM\', \'691\', \'🇫🇲\'), (\'Moldavie\', \'Moldova\', \'MD\', \'MDA\', \'373\', \'🇲🇩\'), (\'Monaco\', \'Monaco\', \'MC\', \'MCO\', \'377\', \'🇲🇨\'), (\'Mongolie\', \'Mongolia\', \'MN\', \'MNG\', \'976\', \'🇲🇳\'), (\'Monténégro\', \'Montenegro\', \'ME\', \'MNE\', \'382\', \'🇲🇪\'), (\'Mozambique\', \'Mozambique\', \'MZ\', \'MOZ\', \'258\', \'🇲🇿\'), (\'Namibie\', \'Namibia\', \'NA\', \'NAM\', \'264\', \'🇳🇦\');');
        $this->addSql('INSERT INTO pays (name_fr, name_en, iso2, iso3, phone_code, flag) VALUES (\'Nauru\', \'Nauru\', \'NR\', \'NRU\', \'674\', \'🇳🇷\'), (\'Népal\', \'Nepal\', \'NP\', \'NPL\', \'977\', \'🇳🇵\'), (\'Nicaragua\', \'Nicaragua\', \'NI\', \'NIC\', \'505\', \'🇳🇮\'), (\'Niger\', \'Niger\', \'NE\', \'NER\', \'227\', \'🇳🇪\'), (\'Nigéria\', \'Nigeria\', \'NG\', \'NGA\', \'234\', \'🇳🇬\'), (\'Norvège\', \'Norway\', \'NO\', \'NOR\', \'47\', \'🇳🇴\'), (\'Nouvelle-Zélande\', \'New Zealand\', \'NZ\', \'NZL\', \'64\', \'🇳🇿\'), (\'Oman\', \'Oman\', \'OM\', \'OMN\', \'968\', \'🇴🇲\'), (\'Ouganda\', \'Uganda\', \'UG\', \'UGA\', \'256\', \'🇺🇬\'), (\'Ouzbékistan\', \'Uzbekistan\', \'UZ\', \'UZB\', \'998\', \'🇺🇿\'), (\'Pakistan\', \'Pakistan\', \'PK\', \'PAK\', \'92\', \'🇵🇰\'), (\'Palaos\', \'Palau\', \'PW\', \'PLW\', \'680\', \'🇵🇼\'), (\'Palestine\', \'Palestine\', \'PS\', \'PSE\', \'970\', \'🇵🇸\'), (\'Panama\', \'Panama\', \'PA\', \'PAN\', \'507\', \'🇵🇦\'), (\'Papouasie-Nouvelle-Guinée\', \'Papua New Guinea\', \'PG\', \'PNG\', \'675\', \'🇵🇬\'), (\'Paraguay\', \'Paraguay\', \'PY\', \'PRY\', \'595\', \'🇵🇾\'), (\'Pays-Bas\', \'Netherlands\', \'NL\', \'NLD\', \'31\', \'🇳🇱\'), (\'Pérou\', \'Peru\', \'PE\', \'PER\', \'51\', \'🇵🇪\'), (\'Philippines\', \'Philippines\', \'PH\', \'PHL\', \'63\', \'🇵🇭\'), (\'Pologne\', \'Poland\', \'PL\', \'POL\', \'48\', \'🇵🇱\'), (\'Portugal\', \'Portugal\', \'PT\', \'PRT\', \'351\', \'🇵🇹\'), (\'Qatar\', \'Qatar\', \'QA\', \'QAT\', \'974\', \'🇶🇦\'), (\'République centrafricaine\', \'Central African Republic\', \'CF\', \'CAF\', \'236\', \'🇨🇫\'), (\'République dominicaine\', \'Dominican Republic\', \'DO\', \'DOM\', \'1809\', \'🇩🇴\'), (\'Tchéquie\', \'Czech Republic\', \'CZ\', \'CZE\', \'420\', \'🇨🇿\'), (\'Roumanie\', \'Romania\', \'RO\', \'ROU\', \'40\', \'🇷🇴\'), (\'Royaume-Uni\', \'United Kingdom\', \'GB\', \'GBR\', \'44\', \'🇬🇧\'), (\'Russie\', \'Russia\', \'RU\', \'RUS\', \'7\', \'🇷🇺\'), (\'Rwanda\', \'Rwanda\', \'RW\', \'RWA\', \'250\', \'🇷🇼\'), (\'Saint-Christophe-et-Niévès\', \'Saint Kitts and Nevis\', \'KN\', \'KNA\', \'1869\', \'🇰🇳\'), (\'Sainte-Lucie\', \'Saint Lucia\', \'LC\', \'LCA\', \'1758\', \'🇱🇨\'), (\'Saint-Marin\', \'San Marino\', \'SM\', \'SMR\', \'378\', \'🇸🇲\'), (\'Saint-Vincent-et-les-Grenadines\', \'Saint Vincent and the Grenadines\', \'VC\', \'VCT\', \'1784\', \'🇻🇨\'), (\'Salomon\', \'Solomon Islands\', \'SB\', \'SLB\', \'677\', \'🇸🇧\'), (\'Salvador\', \'El Salvador\', \'SV\', \'SLV\', \'503\', \'🇸🇻\'), (\'Samoa\', \'Samoa\', \'WS\', \'WSM\', \'685\', \'🇼🇸\'), (\'São Tomé-et-Principe\', \'Sao Tome and Principe\', \'ST\', \'STP\', \'239\', \'🇸🇹\'), (\'Sénégal\', \'Senegal\', \'SN\', \'SEN\', \'221\', \'🇸🇳\'), (\'Serbie\', \'Serbia\', \'RS\', \'SRB\', \'381\', \'🇷🇸\'), (\'Seychelles\', \'Seychelles\', \'SC\', \'SYC\', \'248\', \'🇸🇨\');');
        $this->addSql('INSERT INTO pays (name_fr, name_en, iso2, iso3, phone_code, flag) VALUES (\'Sierra Leone\', \'Sierra Leone\', \'SL\', \'SLE\', \'232\', \'🇸🇱\'), (\'Singapour\', \'Singapore\', \'SG\', \'SGP\', \'65\', \'🇸🇬\'), (\'Slovaquie\', \'Slovakia\', \'SK\', \'SVK\', \'421\', \'🇸🇰\'), (\'Slovénie\', \'Slovenia\', \'SI\', \'SVN\', \'386\', \'🇸🇮\'), (\'Somalie\', \'Somalia\', \'SO\', \'SOM\', \'252\', \'🇸🇴\'), (\'Soudan\', \'Sudan\', \'SD\', \'SDN\', \'249\', \'🇸🇩\'), (\'Soudan du Sud\', \'South Sudan\', \'SS\', \'SSD\', \'211\', \'🇸🇸\'), (\'Sri Lanka\', \'Sri Lanka\', \'LK\', \'LKA\', \'94\', \'🇱🇰\'), (\'Suède\', \'Sweden\', \'SE\', \'SWE\', \'46\', \'🇸🇪\'), (\'Suisse\', \'Switzerland\', \'CH\', \'CHE\', \'41\', \'🇨🇭\'), (\'Suriname\', \'Suriname\', \'SR\', \'SUR\', \'597\', \'🇸🇷\'), (\'Syrie\', \'Syria\', \'SY\', \'SYR\', \'963\', \'🇸🇾\'), (\'Tadjikistan\', \'Tajikistan\', \'TJ\', \'TJK\', \'992\', \'🇹🇯\'), (\'Tanzanie\', \'Tanzania\', \'TZ\', \'TZA\', \'255\', \'🇹🇿\'), (\'Tchad\', \'Chad\', \'TD\', \'TCD\', \'235\', \'🇹🇩\'), (\'Thaïlande\', \'Thailand\', \'TH\', \'THA\', \'66\', \'🇹🇭\'), (\'Timor oriental\', \'East Timor\', \'TL\', \'TLS\', \'670\', \'🇹🇱\'), (\'Togo\', \'Togo\', \'TG\', \'TGO\', \'228\', \'🇹🇬\'), (\'Tonga\', \'Tonga\', \'TO\', \'TON\', \'676\', \'🇹🇴\'), (\'Trinité-et-Tobago\', \'Trinidad and Tobago\', \'TT\', \'TTO\', \'1868\', \'🇹🇹\'), (\'Tunisie\', \'Tunisia\', \'TN\', \'TUN\', \'216\', \'🇹🇳\'), (\'Turkménistan\', \'Turkmenistan\', \'TM\', \'TKM\', \'993\', \'🇹🇲\'), (\'Turquie\', \'Turkey\', \'TR\', \'TUR\', \'90\', \'🇹🇷\'), (\'Tuvalu\', \'Tuvalu\', \'TV\', \'TUV\', \'688\', \'🇹🇻\'), (\'Ukraine\', \'Ukraine\', \'UA\', \'UKR\', \'380\', \'🇺🇦\'), (\'Uruguay\', \'Uruguay\', \'UY\', \'URY\', \'598\', \'🇺🇾\'), (\'Vanuatu\', \'Vanuatu\', \'VU\', \'VUT\', \'678\', \'🇻🇺\'), (\'Vatican\', \'Vatican City\', \'VA\', \'VAT\', \'379\', \'🇻🇦\'), (\'Vénézuéla\', \'Venezuela\', \'VE\', \'VEN\', \'58\', \'🇻🇪\'), (\'Viêt Nam\', \'Vietnam\', \'VN\', \'VNM\', \'84\', \'🇻🇳\'), (\'Yémen\', \'Yemen\', \'YE\', \'YEM\', \'967\', \'🇾🇪\'), (\'Zambie\', \'Zambia\', \'ZM\', \'ZMB\', \'260\', \'🇿🇲\'), (\'Zimbabwe\', \'Zimbabwe\', \'ZW\', \'ZWE\', \'263\', \'🇿🇼\');');
        $this->addSql('ALTER TABLE brand ADD pays_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE brand ADD CONSTRAINT FK_1C52F958A6E44244 FOREIGN KEY (pays_id) REFERENCES pays (id)');
        $this->addSql('CREATE INDEX IDX_1C52F958A6E44244 ON brand (pays_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE pays');
        $this->addSql('ALTER TABLE brand DROP FOREIGN KEY FK_1C52F958A6E44244');
        $this->addSql('DROP INDEX IDX_1C52F958A6E44244 ON brand');
        $this->addSql('ALTER TABLE brand DROP pays_id');
    }
}
